### ISSUE TITLE
Vale Action is slow because it builds Docker image every run

### ISSUE THREAD

**Issue by timotk** [errata-ai/vale-action#105]
# The problem
The Vale Action is slow, because it builds a Docker container every run.

# Example
Here's my Github Action run (54 seconds in total):
<img width="441" alt="image" src="https://github.com/errata-ai/vale-action/assets/6358247/73969f51-36d6-431b-828f-799eb4bb72f9">
- 42 seconds is spent on building the Docker image
- only 5 seconds is spent on downloading packages and running Vale

This is annoying when you update your pull requests often. 

# Ideas
Speed up Vale Action by:
- Use an existing Docker image (for example through [this suggestion](https://github.com/reviewdog/reviewdog/issues/1310))
- Cache the built Docker container yourself using a cache step (not sure how)

Any other ideas?

**Comment by jdkato** [comment]
Yes, this is not good. I'm planning on moving away from ReviewDog entirely, but I haven't had time to work on this.

**Comment by jdkato** [comment]
Should be fixed now.
