### ISSUE TITLE
Error when using ``errata-ai/vale-action@reviewdog`` on workflow

### ISSUE THREAD

**Issue by RobPasMue** [errata-ai/vale-action#107]
We have recently started seeing silent errors in our workflows when using ``errata-ai/vale-action@reviewdog``.

We have a dedicated action tailored for our own repositories that wraps around ``errata-ai/vale-action@reviewdog`` based on the configuration of our repositories. See https://github.com/ansys/actions/blob/main/doc-style/action.yml . Everything was working fine until last week and we believe that the issues are coming from the action itself rather than the Vale binaries.

We had to pin down the following commit  instead of the ``reviewdog`` branch because it was the only one that ensured that things still worked. --> https://github.com/errata-ai/vale-action/commit/13d79669d1c7cf33b26fc5607214ef529f071cdc

The modified branch (and PR) is located here: https://github.com/ansys/actions/pull/345/files

The errors showing up with the ``reviewdog`` branch are the following:

![image](https://github.com/errata-ai/vale-action/assets/37798125/a4dcd60c-610c-470a-b893-d9ab88567528)

We tried defining the ``HOME`` env variable ourselves but it didn't work either. It kept throwing the same error. Since it is a silent error, it is hard to realize about it. If you need further information please let us know!

**Comment by RobPasMue** [comment]
Pinging @jdkato since you are the main maintainer here, any help would be really appreciated. We would love to continue using Vale (and its actions) in its latest versions!

**Comment by jdkato** [comment]
This should be fixed with the latest version of Vale.

**Comment by RobPasMue** [comment]
Thanks, looks like it is solved now! =)
