### ISSUE TITLE
Unable to locate executable file: gem

### ISSUE THREAD

**Issue by iptizer** [errata-ai/vale-action#111]
Last working date: 22. September 2023
First not working day: 27. September 2023

Error message as below.

Environment:
* Self hosted GitHub Actions Runner
* Image: summerwind/actions-runner:latest

Details:
* When switching back to the commit on branch reviewdog to the commit on the 22.09.2023 (https://github.com/errata-ai/vale-action/commit/13d79669d1c7cf33b26fc5607214ef529f071cdc) we are receiving the same issue as illustrated here: https://github.com/errata-ai/vale-action/issues/108

```sh
Run errata-ai/vale-action@reviewdog
  with:
    version: 2.29.6
    token: ***
    files: ["docs/concepts", "docs/how_tos", "docs/references/our_changelog.md", "docs/references/faq.md", "docs/references/glossary.md", "docs/support", "docs/tutorials", "docs/index.md", "docs/getting_started.md", "README.md", "internals.md"]
    filter_mode: added
    fail_on_error: true
    debug: false
    reporter: github-pr-check
    level: error
/usr/bin/pip install docutils
Collecting docutils
  Downloading docutils-0.20.1-py3-none-any.whl (572 kB)
Installing collected packages: docutils
Successfully installed docutils-0.20.1
Error: Error: Unable to locate executable file: gem. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

**Comment by javierhf** [comment]
I'm having the same issue. Apparently you have to add a step to the workflow to install Gems. Then add a _gemfile_ to your repo. I haven't tried the last step yet.

**Comment by jason-seqera** [comment]
Specifically, this works:

```
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
```

No `Gemfile` was required.

**Comment by DanRoscigno** [comment]
> Specifically, this works:
> 
> ```
>       - uses: ruby/setup-ruby@v1
>         with:
>           ruby-version: '3.3'
> ```
> 
> No `Gemfile` was required.

I had to add to the runner PATH:
```
- run: echo "/home/runner/.local/share/gem/ruby/3.3.0/bin" >> $GITHUB_PATH
```
