### ISSUE TITLE
Issue with VALE CLI Latest Release Breaking Workflows

### ISSUE THREAD

**Issue by petcuvio** [errata-ai/vale-action#113]
Hello everyone,

I've encountered a significant issue with the `vale-action` due to `vale cli` where the `latest` tag now points to `3.0.0`. This version introduces configuration changes that are not backwards compatible, causing a disruption in our workflows.

## Description of the Issue

The problem started after the `latest` tag of `vale cli` was updated to `3.0.0`. Our existing configurations are not compatible with this new version, leading to workflow failures. Here's an example of the issue:

![Workflow breakage example](https://github.com/errata-ai/vale-action/assets/53478278/e76f524b-bd6b-4b36-8721-04d3204ecb15)

To mitigate this, I attempted to pin the action to a specific commit (`c99f2dfd2aeaedb3d4bb16f385841830b9164d31`), but it appears that the action still defaults to using the `latest` version of `vale cli`, which doesn't resolve our problem:

![Pinning to a specific commit](https://github.com/errata-ai/vale-action/assets/53478278/f2adb151-f4ff-48dc-ad56-04c62f8c1699)

## Proposed Solution

To ensure stability and prevent such disruptions in future releases, I propose implementing either of the following:

1. **Locking to a Specific Version**: Allow users to lock the action to a specific version of `vale cli` that does not automatically update to the latest.
2. **Clear Versioning Strategy**: Provide a more predictable versioning strategy where major updates do not automatically become the `latest` tag, allowing users to prepare for backward-incompatible changes.

## Classification

I am not sure if this should be classified as a :red_circle: `BUG` or a :large_blue_circle: `FEATURE` request, but I believe addressing this issue is crucial for maintaining stable workflows.

Thank you for your attention to this matter. Looking forward to your thoughts and suggestions.

**Comment by jdkato** [comment]
You can pin the CLI using `version` setting, as shown in the [README](https://github.com/errata-ai/vale-action#version-default-latest).

Not sure the versioning strategy can be more 'clear' than `latest` being the *latest* release. Major releases with breaking changes are rare (2 in ~5 years).

**Comment by petcuvio** [comment]
Busted 😄 

<img height="250px" src="https://media4.giphy.com/media/w89ak63KNl0nJl80ig/giphy.gif?cid=de9bf95e6c0rhy9r3qcugj3queo0w6syt67wu99wxcgqjltb&amp;ep=v1_gifs_search&amp;rid=giphy.gif&amp;ct=g" width="300px" itemtype="http://schema.skype.com/Giphy" key="gif_0">

Did not read the documentation thoroughly.
Testing now ... will of course close the issue. 

@jdkato thanks for the quick reply.
