### ISSUE TITLE
Permission issues when vale-action runs on latest after v3 CLI release

### ISSUE THREAD

**Issue by carolstran** [errata-ai/vale-action#114]
## Description

Following the Vale CLI v3.0.0 release, we've noticed the [vale-action](https://github.com/errata-ai/vale-action) runs into permissions issues that causes the workflow to pass even when errors are present and `fail_on_error` is true.

This happens right after the workflow runs vale with reviewdog:

<img width="597" alt="Screenshot 2024-01-11 at 17 01 30" src="https://github.com/errata-ai/vale-action/assets/26869552/244bab42-2156-408b-921d-c55f3bf4b660">

> [!WARNING]
> You also have the [same issue](https://github.com/errata-ai/vale/actions/runs/7483507163/job/20368862376#step:3:53) in your `runner / vale` job run on the Vale CLI repo.

<details><summary>Screenshot (in case the logs expire)</summary>
<img width="1498" alt="Screenshot 2024-01-11 at 15 46 09" src="https://github.com/errata-ai/vale-action/assets/26869552/763174a3-a267-413c-a21a-1a72b6b3089a">
</details> 

I opened a pull request with known issues and used [tmate](https://github.com/mxschmitt/action-tmate) to reproduce the action. Then when running the same command (but with sudo permissions), it produces the expected output.

<details><summary>Screenshot of tmate repro output</summary>
<img width="1189" alt="Screenshot 2024-01-11 at 15 57 37" src="https://github.com/errata-ai/vale-action/assets/26869552/4ba0dfbf-1a10-4b61-b647-a93c6e7177a4">
</details> 

## Vale versions

- Introduced with `3.0.0` and persists with `3.1.1`
- `2.30.0` or lower works as expected (if you revert the folder structure changes for Vocabularies)

### 3.0.0

Shows `mkdir /.local: permission denied` 

[Job logs](https://github.com/emnify/product-docs/actions/runs/7480642934/job/20360522844#step:3:45)

<details><summary>Screenshot (in case the logs expire)</summary>
<img width="1280" alt="Screenshot 2024-01-11 at 14 48 19" src="https://github.com/errata-ai/vale-action/assets/26869552/4c263851-f1e6-4a15-bb04-e50c18301752">
</details> 

### 2.30.0

Works as expected (this run should fail because there are known errors in this PR)

[Job logs](https://github.com/emnify/product-docs/actions/runs/7491502094/job/20392860685?pr=237#step:3:45)

<details><summary>Screenshot (in case the logs expire)</summary>
<img width="1075" alt="Screenshot 2024-01-11 at 17 17 08" src="https://github.com/errata-ai/vale-action/assets/26869552/8d3ec6fc-8d1b-4ef0-99e3-da2bb6f4b486">
</details> 

## Environment

My default workflow ([source code](https://github.com/emnify/product-docs/blob/main/.github/workflows/vale.yml)):

```yml
jobs:
  vale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: errata-ai/vale-action@reviewdog
        with:
          fail_on_error: true
          vale_flags: "--minAlertLevel=error"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

```
GITHUB_TOKEN Permissions
  Actions: write
  Checks: write
  Contents: write
  Deployments: write
  Discussions: write
  Issues: write
  Metadata: read
  Packages: write
  Pages: write
  PullRequests: write
  RepositoryProjects: write
  SecurityEvents: write
  Statuses: write
```

I've also tried...
- Setting explicit GITHUB_TOKEN permissions 
- Defining the `token` input explicitly
- Setting up the env file earlier in the action

**Comment by jdkato** [comment]
This should be fixed now.

**Comment by carolstran** [comment]
@jdkato Thanks so much! Out of curiosity, what was the issue and which commit fixed it?
