### ISSUE TITLE
Spell checking running even after toggling off

### ISSUE THREAD

**Issue by tjperry07** [errata-ai/vale-action#124]
Currently Vale VS Code extension is running spell check across all files. Turning this off in settings, doing a restart of VS code doesn't stop the spell checking.

**Comment by ChrisChinchilla** [comment]
@tjperry07 Sorry to be annoying, but I think this was meant for the VSCode repo? I can't transfer this as I don't have permissions to this repo, but I'll recreate it and tag you there.

**Comment by tjperry07** [comment]
So sorry, I wasn't paying attention.
