### ISSUE TITLE
Bump reviewdog version to 0.20.1

### ISSUE THREAD

**Issue by SMoraisAnsys** [errata-ai/vale-action#131]
Hi, I was wondering if this action could use a more recent version of `reviewdog`.

Currently, the version used is `0.17` 
https://github.com/errata-ai/vale-action/blob/91ac403e8d26f5aa1b3feaa86ca63065936a85b6/src/input.ts#L61
while the most recent version is currently `0.20.1`

One of the gain from changing the version would be to leverage `-fail-level` instead of `-fail-on-error`.
I don't know if you are open to the idea of adding back the `level` input which was removed previously (https://github.com/errata-ai/vale-action/commit/c4213d4de3d5f718b8497bd86161531c78992084). Since I couldn't find information on why it got removed, maybe that one of the reason for such limitation was the lack of feature in `reviewdog` and using the new version might help on this.

More information:
- [-fail-level impact on exit code](https://github.com/reviewdog/reviewdog?tab=readme-ov-file#exit-codes)
- [-fail-on-error deprecation](https://github.com/reviewdog/reviewdog/blob/master/CHANGELOG.md#rotating_light-deprecation-warnings)

**Comment by jdkato** [comment]
Yes, I'll update when I get a chance (PRs are also welcome).

You can also currently change the version of reviewdog by providing a value for [`reviewdog_url`](https://github.com/errata-ai/vale-action/blob/91ac403e8d26f5aa1b3feaa86ca63065936a85b6/action.yml#L58), although this won't help in cases where new features aren't yet supported in this action.

**Comment by SMoraisAnsys** [comment]
Cool, I'll give it a try then ! Thanks for confirming that you are not against this changes :)

**Comment by anaxite** [comment]
I'm having a go at this request, and would appreciate feedback on the PR when possible.

Does it make sense to re-add the `level` input at the same time, or do it later? I'm leaving the PR as draft until I'm sure.

**Comment by anaxite** [comment]
@SMoraisAnsys Go ahead and test the new version. I saw one of the workflows was failing, though (https://github.com/errata-ai/vale-action/actions/runs/11849732087/job/33023465079)
