### ISSUE TITLE
Providing path to .vale.ini file

### ISSUE THREAD

**Issue by RobPasMue** [errata-ai/vale-action#68]
Is it possible to tell the vale-action the location of a .vale.ini file? 
Instead of expecting it at the root directory of the repository...

I tried providing it as a `vale_flag` argument: `"--config='my/path/to/.vale.ini'"` but it didn't work. Failure occured in `vale sync` step since it was not considering its location.

I would be interested in this feature if possible. I don't know if it is already available.

**Comment by RobPasMue** [comment]
This applies to the vale-action/reviewdog branch of course, which is the default branch of the repository. I see that in master there are some other possible arguments, but I'd prefer to keep the reviewdog.

**Comment by jdkato** [comment]
Yes, this was an oversight. It'll be fixed in the next release.

**Comment by RobPasMue** [comment]
Great, thanks @jdkato! Much appreciated.

**Comment by jdkato** [comment]
This should be fixed now.
