### ISSUE TITLE
Vale action output showing up under different workflow

### ISSUE THREAD

**Issue by heitortsergent** [errata-ai/vale-action#73]
I'm trying to add the vale-action to the Stoplight docs repository ([this PR](https://github.com/stoplightio/platform-docs/pull/452)), and for some reason the reviewdog output with the annotations for the vale-action is being added under another workflow we have in our repo for checking markdown links:

<img width="1006" alt="Screen Shot 2022-07-11 at 3 30 50 PM" src="https://user-images.githubusercontent.com/446316/178352759-a3f16d3c-a5f4-4d57-9833-bafd395d7e3e.png">

Any ideas on why that might be happening? I tried removing the `markdown-link-check` workflow to see what happens, and that makes the reviewdog vale report show up correctly under the vale action.

**Comment by erezrokah** [comment]
Adding another case of this issue in https://github.com/cloudquery/cloudquery/pull/4413
![image](https://user-images.githubusercontent.com/26760571/201518313-5f53172f-082c-430e-89ba-68fc402d0de4.png)

Vale is showing up failed on an unrelated PR Labeler action

**Comment by Jan0707** [comment]
I am encountering the same issue. Vale's result do show up in a different action entirely.

**Comment by prcr** [comment]
Also happens to me (I had previously opened https://github.com/errata-ai/vale-action/issues/57).

**Comment by DaemonLoki** [comment]
Encountering a similar issue. Is there any hint on what might cause this, yet?

**Comment by heitortsergent** [comment]
Did some digging around, and this seems to be an issue with GitHub Actions and its API, and it's been around for a while now:

https://github.com/orgs/community/discussions/24616

And feedback from more people on the reviewdog project: https://github.com/reviewdog/reviewdog/issues/403

It doesn't seem like this will be fixed anytime soon, so I think it might be better to just close this issue for now.
