### ISSUE TITLE
Vale action flags text within an ignored class

### ISSUE THREAD

**Issue by nickvigilante** [errata-ai/vale-action#92]
See this PR: https://github.com/cockroachdb/docs/pull/15847/files#diff-a5215694f34792b17558dbac00935f34f33365e310715b0da747ce2536bb6909R297

I added a simple `div` block with the `release-note-contributors` class, and while the command line Vale successfully ignores the `div`, the action is not.

**Comment by jdkato** [comment]
Whenever there's a behavior mismatch between the CLI/action, it's probably due to the action using a different version.

It looks like you pin an older [version here](https://github.com/cockroachdb/docs/blob/4d7299e488da9010cf88394af1fecc6890c86ae8/.github/workflows/vale.yml#L26).

**Comment by nickvigilante** [comment]
Thanks. Removing that line seemed to do it. Out of curiosity, is there a list of supported versions? I pulled what was available in the readme: https://github.com/errata-ai/vale-action#version-default-latest

**Comment by jdkato** [comment]
As stated on that page, any version >= 2.16.0. If you don't specify one, it will default to the latest (although, for CI purposes, I'd suggest specifying one).
