### ISSUE TITLE
Action didn't fail for configuration error in `.yml` files

### ISSUE THREAD

**Issue by kayx23** [errata-ai/vale-action#97]
Noticed reviewdog would pass in the following situations, where I think it should fail. 

## Example 1
![image](https://user-images.githubusercontent.com/39619599/236806422-df140985-c024-4c07-9df2-355afc326a86.png)

![image](https://user-images.githubusercontent.com/39619599/236806380-1b99b8b7-f29d-4be9-80ef-262fcb342af6.png)

[Link to the action](https://github.com/kayx23/vale-tests/actions/runs/4914276114/jobs/8775388993?pr=1)

## Example 2
Here I copy pasted the `.yml` config over and did not notice the incorrect indentation from line 2 and onwards. Reviewdog seems to pass but in reality it errored out: 
![image](https://user-images.githubusercontent.com/39619599/236807107-e0ddb41a-d038-4110-a8c5-87db7be5a80d.png)

[Link to the action](https://github.com/kayx23/vale-tests/actions/runs/4914064797/jobs/8774948170)

**Comment by rmoff** [comment]
Adding another example of this problem. My vale config had the wrong case for a styles folder. The action still returned a success status though. 

![CleanShot 2024-10-02 at 09 53 14](https://github.com/user-attachments/assets/46ed1395-b07e-4ba0-a626-981bc82c1342)

![CleanShot 2024-10-02 at 09 53 03](https://github.com/user-attachments/assets/32ab61d9-a883-47ef-9453-bd355bb0f1a0)
